# Generated by Django 5.2 on 2025-05-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='submitted_at',
            new_name='created_at',
        ),
    ]
